apiVersion: ethereum2.kotal.io/v1alpha1
kind: BeaconNode
metadata:
  name: teku-beacon
  namespace: eth-nodes
spec:
  client: teku
  # This is the network-config specified in the teku-beacon configmap. Kotal will mount this file from the configmap
  # into a volume inside the pod on below location.
  network: "/opt/teku/kotal-config/network-config.yaml"
  image: consensys/teku:develop
  logging: info
  rest: true
  restPort: 8888
  executionEngineEndpoint: http://geth:8551
  jwtSecretName: "jwt-secret"
  feeRecipient: "0x0000000000000000000000000000000000000000"
  resources:
    cpu: "1"
    memory: "1Gi"